{
	"version": 1577047846,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/text.png",
		"images/btnplay-sheet0.png",
		"images/btnsound-sheet0.png",
		"images/btnsound-sheet1.png",
		"images/sprite10-sheet0.png",
		"images/txtscore.png",
		"images/splash-sheet0.png",
		"images/title-sheet0.png",
		"images/cloud-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/btnback-sheet0.png",
		"images/line-sheet0.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/citybg-sheet0.png",
		"images/bg-sheet0.png",
		"images/speedup-sheet0.png",
		"images/jump-sheet0.png",
		"images/jump-sheet1.png",
		"images/sky-sheet0.png",
		"images/smallitem-sheet0.png",
		"images/smallitem-sheet1.png",
		"images/bar-sheet0.png",
		"images/chain.png",
		"images/tube-sheet0.png",
		"images/tubedown-sheet0.png",
		"images/tubeupsolid-sheet0.png",
		"images/birdfly-sheet0.png",
		"images/birdfly-sheet1.png",
		"images/train-sheet0.png",
		"images/traindown-sheet0.png",
		"images/fallbin-sheet0.png",
		"images/fallbin-sheet1.png",
		"images/pool-sheet0.png",
		"images/pooldown-sheet0.png",
		"images/downbg-sheet0.png",
		"images/waterflow-sheet0.png",
		"images/waterflow-sheet1.png",
		"images/hole-sheet0.png",
		"images/holedown-sheet0.png",
		"images/dust-sheet0.png",
		"images/tree-sheet0.png",
		"images/tree-sheet1.png",
		"images/bushes-sheet0.png",
		"images/light-sheet0.png",
		"media/coin.ogg",
		"media/car-skids-and-crashes_g1hmrre_.ogg",
		"media/duck 2.ogg",
		"media/falling sound 3 .ogg",
		"media/gym bag drop sound effect royalty.ogg",
		"media/medium water splashes .ogg",
		"media/metal-stamp.ogg",
		"media/music midnight city production music royalty.ogg",
		"media/ssm-102518-skateboard-inst.ogg",
		"media/lose.ogg",
		"media/rubbish.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}